### ISSUE TITLE
Link not working.

### ISSUE THREAD

**Issue by sarthakkathpalia** [ecker-lab/sensorium_2023#3]
The .zip link to download the data on the [repo](https://github.com/ecker-lab/sensorium_2023#starter-kit) shows a 404 error. 
<img width="858" alt="image" src="https://github.com/ecker-lab/sensorium_2023/assets/85081359/f26c3974-1ca5-499d-8cc1-89bf1975be84">

**Comment by Mvystrcilova** [comment]
This is because a new dataset is not yet available. We had to gather a new one because of leaked test responses. We will notify everyone once the new dataset is available.

**Comment by wangkaihong** [comment]
Hi,

Thanks for releasing this amazing contest! I am wondering if you are close to releasing the new version of the dataset. If not, do you have an estimated time? Thanks again!

**Comment by Mvystrcilova** [comment]
Hi @wangkaihong, the new dataset it already released. Here is the link: https://gin.g-node.org/pollytur/sensorium_2023_dataset

**Comment by Mvystrcilova** [comment]
Hi @zhuyu-cs, yes it does indeed but when you look at the values in the test response files, there should be dummy labels with plain zeros.

**Comment by zhuyu-cs** [comment]
> Hi @zhuyu-cs, yes it does indeed but when you look at the values in the test response files, there should be dummy labels with all zeros.

Got it! That is a useful setting for the dataloader. Thanks for yout explanation!

By the way, will you release the GT of these subsets, 'final_test_main', 'live_test_main', 'final_test_main' and 'final_test_bonus' in **[the first released dataset](https://gin.g-node.org/pollytur/Sensorium2023Data)**? I think it might be fairer to later participants if it was public. Thanks anyway :)

**Comment by pollytur** [comment]
@zhuyu-cs Here is the new dataset - https://gin.g-node.org/pollytur/sensorium_2023_dataset , here is the old one https://gin.g-node.org/pollytur/Sensorium2023Data , so both are still publicly available. Hope this helps
