### ISSUE TITLE
submission error

### ISSUE THREAD

**Issue by wangkaihong** [ecker-lab/sensorium_2023#4]
Hi,

I am trying to submit an initial result I got from the example code, predictions_file_live_test_main_main_track.parquet.brotli, at https://codalab.sensorium-competition.net/competitions/9#participate-submit_results

![image](https://github.com/ecker-lab/sensorium_2023/assets/23068166/792229c8-4e19-4e68-af01-8a614e6d243c)

but the website returns:

![image](https://github.com/ecker-lab/sensorium_2023/assets/23068166/2ebc5b2e-a0ea-47c5-a7f5-56b027d7ae9b)

I am wondering if the website is experiencing some error or did I missed anything?

Thanks!

**Comment by RickWayne1125** [comment]
> Participants should submit a zip file with 2 files in it : predictions_live_main.parquet.brotli and predictions_final_main.parquet.brotli for the live and final test correspondingly. For the bonus track please replace main with ood like this : predictions_final_ood.parquet.brotli.

I think you should put both the live test file and the final test file in a single zip file. And also the auto-generated filename is incorrect, you need to rename the file in the format above.
