### ISSUE TITLE
Bonus Track - Submission Error

### ISSUE THREAD

**Issue by zhuyu-cs** [ecker-lab/sensorium_2023#9]
1. There are two datasets,  old (https://gin.g-node.org/pollytur/Sensorium2023Data) and new (https://gin.g-node.org/pollytur/sensorium_2023_dataset), where the *main track* has been updated to use the new data for the competition. But it is not clear about the OOD track if it has been updated.
2. I tried to use the same save strategy, i.e. skip 50 steps, on the *OOD track*, and submit with the old dataset  (https://gin.g-node.org/pollytur/Sensorium2023Data), but it showed that the frames don't match. Is this a special operation against *OOD track*? Because on the *main track* my save strategy is fine after submitting. Here is the error log:

`Traceback (most recent call last):
  File "/tmp/codalab/tmpm4mblJ/run/program/score.py", line 607, in 
    assert i == j, 'Make sure the predictions have correct shapes. Should be np.array with shape (num of neurons, video_frames - 50), like (7400, 250) for a video with 300 frames'
AssertionError: Make sure the predictions have correct shapes. Should be np.array with shape (num of neurons, video_frames - 50), like (7400, 250) for a video with 300 frames`

**Comment by zhuyu-cs** [comment]
By the way, another problem appears when entering the contest URL (https://codalab.sensorium-competition.net/), which leads to the failed submission.

`This server could not prove that it is codalab.sensorium-competition.net; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Tuesday, August 29, 2023. Does that look right? If not, you should correct your system's clock and then refresh this page.`

**Comment by pollytur** [comment]
Thanks for letting us know! I will check why certificates were not updated automatically and fix it.

**Comment by pollytur** [comment]
the certificate is updated! Thanks for letting us know one more time

**Comment by pollytur** [comment]
1. Yes, OOD was also updated. As there were no participants submissions, we did not renewed the competition
2. It should be 249 frames mostly as most of videos are 299 frames

**Comment by zhuyu-cs** [comment]
> the certificate is updated! Thanks for letting us know one more time

Thanks for your work.



> 1. Yes, OOD was also updated. As there were no participants submissions, we did not renewed the competition
> 2. It should be 249 frames mostly as most of videos are 299 frames

Maybe they are just not ready before like me. By the way, I'm really interesting in the OOD track since it is important for bio-researchers to design a generalized digital twin. If convenient, please still consider opening this contest, thank you.

**Comment by aecker** [comment]
As far as I understand the OOD track is open. It's just not called "[new]" because there had been no submissions yet.

@pollytur maybe rename it on CodaLab to make this clear?

**Comment by zhuyu-cs** [comment]
Actually, I have tried 3 times with old or new dataset. The test data on CodaLab is `**old**` one [(https://gin.g-node.org/pollytur/Sensorium2023Data)](url), since the uploaded results of new dataset would raise an error like

`assert set(solutions['mouse'].unique().tolist()) == set(predictions['mouse'].unique().tolist()), \
AssertionError: Mice are different in predictions. Mice column should contain all of the following values ['dynamic29156-11-10-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29228-2-10-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29234-6-9-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29513-3-5-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29514-2-9-Video-8744edeac3b4d1ce16b680916b5267ce']`

At the same time, the results of new one would cause another issuse, as mention before:

> 2. I tried to use the same save strategy, i.e. skip 50 steps, on the _OOD track_, and submit with the old dataset  (https://gin.g-node.org/pollytur/Sensorium2023Data), but it showed that the frames don't match. Is this a special operation against _OOD track_? Because on the _main track_ my save strategy is fine after submitting. Here is the error log:
> 
> `Traceback (most recent call last): File "/tmp/codalab/tmpm4mblJ/run/program/score.py", line 607, in assert i == j, 'Make sure the predictions have correct shapes. Should be np.array with shape (num of neurons, video_frames - 50), like (7400, 250) for a video with 300 frames' AssertionError: Make sure the predictions have correct shapes. Should be np.array with shape (num of neurons, video_frames - 50), like (7400, 250) for a video with 300 frames`

I have carefully checked the old dataset and confirmed that the toal frames of input videos are 299 or 300. Thus, I would upload results, each result in it has 249 or 250 timesteps. But I still got the error like the above.

**Comment by Mvystrcilova** [comment]
> Actually, I have tried 3 times with old or new dataset. The test data on CodaLab is `**old**` one [(https://gin.g-node.org/pollytur/Sensorium2023Data)](url), since the uploaded results of new dataset would raise an error like
> 
> `assert set(solutions['mouse'].unique().tolist()) == set(predictions['mouse'].unique().tolist()), \ AssertionError: Mice are different in predictions. Mice column should contain all of the following values ['dynamic29156-11-10-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29228-2-10-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29234-6-9-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29513-3-5-Video-8744edeac3b4d1ce16b680916b5267ce', 'dynamic29514-2-9-Video-8744edeac3b4d1ce16b680916b5267ce']`
> 
> At the same time, the results of new one would cause another issuse, as mention before:
> 
> > 2. I tried to use the same save strategy, i.e. skip 50 steps, on the _OOD track_, and submit with the old dataset  (https://gin.g-node.org/pollytur/Sensorium2023Data), but it showed that the frames don't match. Is this a special operation against _OOD track_? Because on the _main track_ my save strategy is fine after submitting. Here is the error log:
> > 
> > `Traceback (most recent call last): File "/tmp/codalab/tmpm4mblJ/run/program/score.py", line 607, in assert i == j, 'Make sure the predictions have correct shapes. Should be np.array with shape (num of neurons, video_frames - 50), like (7400, 250) for a video with 300 frames' AssertionError: Make sure the predictions have correct shapes. Should be np.array with shape (num of neurons, video_frames - 50), like (7400, 250) for a video with 300 frames`
> 
> I have carefully checked the old dataset and confirmed that the toal frames of input videos are 239, 299 or 300. Thus, I would upload results, each result in it has 189, 249 or 250 timesteps. But I still got the error like the above. I think this is the reason why OOD track has no results, not that no one has submitted.

Have you tried setting offset in the dataloader to 0 instead of -1? Maybe it could help.

**Comment by bryanlimy** [comment]
I am also having a problem in making submissions to the OOD track.

I received the following pop-up message from the browser after uploading the `.zip` file:

```
codalab.sensorium-competition.net says:

Sorry, failed to upload file.
```

and I see the following error message in the browser console:
```
POST https://s3.gwdg.de/sensorium2023-private 400 (Bad Request)
request @ scripts.js:32
upload @ scripts.js:108
(anonymous) @ scripts.js:141
req.onload @ scripts.js:20
load (async)
request @ scripts.js:19
getUploadURL @ scripts.js:136
```

**Comment by pollytur** [comment]
@bryanlimy The issue is probably due to the file size. 
I am sorry for the long reply here, we have updated the instructions some time ago, upload the live and final zip files separately. (click participate -> submit/view results there you would see colourful tabs with `Development` and `Final`. Please upload live and final predictions here correspondingly. Please upload both as you would not be able to win if the final test set submission is missing.)
Please let us know if this helps!

**Comment by zhuyu-cs** [comment]
> @bryanlimy The issue is probably due to the file size. I am sorry for the long reply here, we have updated the instructions some time ago, upload the live and final zip files separately. (click participate -> submit/view results there you would see colourful tabs with `Development` and `Final`. Please upload live and final predictions here correspondingly. Please upload both as you would not be able to win if the final test set submission is missing.) Please let us know if this helps!

Thanks for your reply. I have tried as your suggestion, but it not work. Could you share the shape of 'live_test_ood' and 'final_test_ood' for the newly 5 mice? like, (249, 7440) for mice-xx.

**Comment by pollytur** [comment]
@zhuyu-cs for the videos with 300 frames and longer we expect 249 frames (limit the video to 300 frames - this is should happen automatically with the dataloaders from the toolkit), for the shorter videos we expect 189 frames. Hope this helps

**Comment by zhuyu-cs** [comment]
It works! Thanks for your help!
